name: arteligent
favicon: null
layout_spectrum: 0.75241
typography_spectrum: 0.2569352937862277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.10158609692007303
  lightness: 0.20204033656045794
  saturation: 0.6561326661612839
  rhythmicContrast: 0.4819800863042474
purpose: []
